// API Route for PDF Export
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { auth } from '@/lib/auth';
import { exportLimiter, checkRateLimit } from '@/lib/rate-limit';
import { validateBody, exportSchema } from '@/lib/validations';
import { generateInteriorPDF, generateCoverPDF, generateFullExport } from '@/services/pdf';
import type { TrimSize } from '@/types';
import JSZip from 'jszip';

export async function POST(request: NextRequest) {
  try {
    // Rate limit: 5 exports per minute per user/IP
    const session = await auth();
    const identifier = session?.user?.id || request.headers.get('x-forwarded-for') || 'anonymous';
    const rateLimitResponse = await checkRateLimit(exportLimiter, 5, identifier);
    if (rateLimitResponse) return rateLimitResponse;

    // Validate input
    const parsed = await validateBody(request, exportSchema);
    if (parsed.error) return parsed.error;

    const {
      bookId,
      trimSize,
      includePageNumbers,
      includeCover,
      coverTitle,
      coverAuthor,
      coverBackText,
    } = parsed.data;

    // Fetch book with pages
    const book = await prisma.book.findUnique({
      where: { id: bookId },
      include: {
        pages: {
          orderBy: { pageNumber: 'asc' },
        },
      },
    });

    if (!book) {
      return NextResponse.json(
        { error: 'Book not found' },
        { status: 404 }
      );
    }

    if (book.pages.length === 0) {
      return NextResponse.json(
        { error: 'Book has no pages' },
        { status: 400 }
      );
    }

    const imagePaths = book.pages.map((p: { imagePath: string }) => p.imagePath);
    const title = coverTitle || book.title;

    // Generate PDFs
    let interiorPDF: Buffer;
    let coverPDF: Buffer | null = null;

    if (includeCover) {
      const result = await generateFullExport(
        {
          trimSize: trimSize as TrimSize,
          imagePaths,
          includePageNumbers,
        },
        {
          trimSize: trimSize as TrimSize,
          pageCount: book.pages.length * 2, // Pages × 2 for single-sided
          title,
          author: coverAuthor,
          backText: coverBackText || `A delightful coloring book for children. ${book.pages.length} unique pages to color and enjoy!`,
        }
      );
      interiorPDF = result.interior;
      coverPDF = result.cover;
    } else {
      interiorPDF = await generateInteriorPDF({
        trimSize: trimSize as TrimSize,
        imagePaths,
        includePageNumbers,
      });
    }

    // Create ZIP file with both PDFs
    const zip = new JSZip();
    const safeName = book.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();

    zip.file(`${safeName}-interior.pdf`, interiorPDF);
    if (coverPDF) {
      zip.file(`${safeName}-cover.pdf`, coverPDF);
    }

    // Add readme
    const readme = `
# ${book.title} - KDP Export Package

## Contents
- ${safeName}-interior.pdf - Book interior (${book.pages.length} coloring pages)
${coverPDF ? `- ${safeName}-cover.pdf - Book cover with spine` : ''}

## KDP Upload Instructions

1. Go to kdp.amazon.com and sign in
2. Click "Create" > "Paperback"
3. Fill in book details (title, author, description)
4. Upload interior PDF: ${safeName}-interior.pdf
${coverPDF ? `5. Upload cover PDF: ${safeName}-cover.pdf` : '5. Use KDP Cover Creator or upload your own cover'}
6. Set pricing and publish!

## Specifications
- Trim Size: ${trimSize}" 
- Interior: Black & White
- Paper: White
- Page Count: ${book.pages.length * 2} (single-sided printing)

## Notes
- PDFs are formatted to KDP specifications
- Ensure your content complies with KDP guidelines
- Review the preview before publishing

Generated by Kids Book Creator
    `.trim();

    zip.file('README.txt', readme);

    // Generate ZIP
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' });

    // Update book status
    await prisma.book.update({
      where: { id: bookId },
      data: { status: 'exported' },
    });

    // Return ZIP file
    return new NextResponse(new Uint8Array(zipBuffer), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${safeName}-kdp-package.zip"`,
      },
    });
  } catch (error) {
    console.error('Export failed:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Export failed' },
      { status: 500 }
    );
  }
}
